apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  namespace: sample-service
  labels:
    app: order-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
      - name: order-service
        image: docker.sds-act.com/order-service:latest
        ports:
        - containerPort: 8080
        env:
        - name: RABBITMQ_SERVER_URL
          value: "rabbitmq"
