apiVersion: v1
kind: Service
metadata:
  name: order-service
spec:
  selector:
    app: order-service
  ports:
  - nodePort: 31982
    protocol: TCP
    port: 8080
    targetPort: 8080
  type: NodePort
