apiVersion: v1
kind: Service
metadata:
  labels:
    name: mongo
  name: mongo-svc
spec:
  ports:
  - port: 27017
    protocol: TCP
    targetPort: 27017
  selector:
    role: mongo
  sessionAffinity: None
  type: NodePort
