apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: mariadb
spec:
  serviceName: "mariadb"
  updateStrategy:
    type: RollingUpdate
  replicas: 1
  template:
    metadata:
      labels:
        role: "mariadb"
        environment: development
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: mariadb
        image: mariadb
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "jeep8walrus"
        - name: MYSQL_ALLOW_EMPTY_PASSWORD
          value: "yes"
        volumeMounts:
        - name: local-claim
          mountPath: /var/lib/mysql
  volumeClaimTemplates:
  - metadata:
      name: local-claim
    spec:
      accessModes:
      - ReadWriteOnce
      storageClassName: local-mariadb-storage
      resources:
        requests:
          storage: 1Gi