apiVersion: v1
kind: Service
metadata:
  name: email-service
  namespace: sample-service
spec:
  selector:
    app: email-service
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  type: ClusterIP
