apiVersion: apps/v1
kind: Deployment
metadata:
  name: email-service
  namespace: sample-service
  labels:
    app: email-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: email-service
  template:
    metadata:
      labels:
        app: email-service
    spec:
      containers:
      - name: email-service
        image: docker.sds-act.com/email-service:latest
        ports:
        - containerPort: 8080
        env:
        - name: RABBITMQ_SERVER_URL
          value: "rabbitmq"
