apiVersion: v1
kind: PersistentVolume
metadata:
 name: pv-sampel-service-rabbitmq
spec:
 capacity:
   storage: 5Gi
 accessModes:
 - ReadWriteOnce
 persistentVolumeReclaimPolicy: Retain
 storageClassName: sample-service-rabbitmq-storage
 local:
   path: /home/actmember/workspace/rabbitmq/data
 nodeAffinity:
   required:
     nodeSelectorTerms:
     - matchExpressions:
       - key: kubernetes.io/hostname
         operator: In
         values:
         - act-kube-02
