apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx
data:
  # Adding new entries here will make them appear as files in the deployment.
  # Please update k8s.io/k8s.io/README.md when you update this file
  nxs-nginx.conf: |
    server {

      server_name _;

      index index.html;
      proxy_http_version       1.1;
      proxy_set_header         Connection "";
      proxy_connect_timeout    2;
      proxy_next_upstream      error timeout invalid_header http_500;

      location ^~ /api/ {
        client_max_body_size 500m;
        proxy_pass http://nginx-ingress-controller;
      }

      location / {
        limit_except GET HEAD POST PUT DELETE {
            deny all;
        }
        try_files $uri $uri/ @rewrites;
      }

      location @rewrites { rewrite ^(.+)$ /index.html last; }

      root /var/www/html;

    }
